language: go

go:
  - 1.12.x
  - 1.13.x

env: GO111MODULE=on
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/lint/golint
  - go get github.com/rakyll/gotest
  - go get honnef.co/go/tools/cmd/staticcheck

script:
  - go vet ./handler
  - go vet -tags=test ./handler
  - golint ./handler
  - staticcheck ./handler
  - staticcheck -tags=heroku ./handler
  - staticcheck -tags=container ./handler
  # - staticcheck -tags=test ./handler
  - gotest -v -tags test -cover -covermode=count -coverprofile coverage.out ./...

after_success:
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
